### ISSUE TITLE
[Typo] Misspelled Theme constant

### ISSUE THREAD

**Issue by aruray-ms** [pyramid-scheme-ceo/react-teams-tab#5]
Change it to `contrast`

https://github.com/pyramid-scheme-ceo/react-teams-tab/blob/b6ead9452af787c2a37885392944a05d83241ebd/src/constants.ts#L2

**Comment by aruray-ms** [comment]
This is resulting in the theme not rendering

**Comment by pyramid-scheme-ceo** [comment]
Hi @aruray-ms, firstly sorry for the very late response - I don't monitor this repo too often - but thanks for pointing it out to me, it's fixed in linked PR :)
